# Generated by Django 4.0.5 on 2022-09-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='security',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='security',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
