# Generated by Django 4.0.5 on 2022-09-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_citizen_first_name_remove_citizen_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
