# Generated by Django 4.0.5 on 2022-09-27 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_security_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
    ]
