# Generated by Django 4.1.2 on 2023-01-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_full_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='citizen',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
