# Generated by Django 4.1.2 on 2022-12-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='friends',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
