# Generated by Django 4.1.2 on 2022-12-06 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_citizen_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='friends',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
