# Generated by Django 4.1.2 on 2022-12-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_citizen_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='friends',
            field=models.ManyToManyField(to='user.citizen'),
        ),
    ]
