# Generated by Django 4.1.2 on 2022-12-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_citizen_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='friends',
            field=models.ManyToManyField(blank=True, to='user.citizen'),
        ),
    ]
