version: '3.3'

services:
  django:
    container_name: django
    build: ./backend
    command: gunicorn usurpa.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    links:
      - db:db
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - static_volume:/usr/src/backend/django_static
    
  db:
    container_name: db
    image: postgis/postgis
    ports:
      - 5432:5432
    networks:
      - backend
    env_file:
      - ./.env
    environment:
      POSTGRES_USER : $SQL_USER
      POSTGRES_PASSWORD : $SQL_PASSWORD

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
        - ./docker/nginx/certbot/conf:/etc/letsencrypt
        - ./docker/nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  backend:
    driver: bridge

volumes:
  static_volume:

  