# Generated by Django 4.1.2 on 2023-01-18 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'REQUESTED'), (1, 'ACCEPTED'), (2, 'IN PROGRESS'), (3, 'COMPLETED'), (4, 'CANCELLED')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'REQUESTED'), (1, 'ACCEPTED'), (2, 'IN PROGRESS'), (3, 'COMPLETED'), (4, 'CANCELLED')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.emergency')),
            ],
        ),
    ]
