# Generated by Django 4.0.5 on 2022-09-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'REQUESTED'), (1, 'ACCEPTED'), (2, 'IN PROGRESS'), (3, 'COMPLETED')], default=0),
        ),
    ]
