# Generated by Django 4.0.5 on 2022-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_alter_emergency_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
