# Generated by Django 4.0.5 on 2022-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_alter_emergency_created_alter_emergency_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
