# Generated by Django 4.0.5 on 2022-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_alter_emergency_created_alter_emergency_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'REQUESTED'), (1, 'ACCEPTED'), (2, 'IN PROGRESS'), (3, 'COMPLETED'), (4, 'CANCELLED')], default=0),
        ),
    ]
