# Generated by Django 4.0.5 on 2022-10-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_alter_emergency_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'REQUESTED'), (1, 'ACCEPTED'), (2, 'IN PROGRESS'), (3, 'COMPLETED'), (4, 'CANCELLED')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.emergency')),
            ],
        ),
    ]
